function [datOut,minsN,minNFull] = abbvMins(datIn,dType)

%here dType = 1 for vector, 2 for rows of grains and columns of minerals (mnrlMtx),
%and 3 for a mineral correlation matrix.   [4,5,6,7,9,10,11,12,14,15,18,19,21,22,27,28]


minsN = {'blank','Qtz','Ksp','Ab','An25','AN50','An75','Mscv','Bti low','Bti Mg','Bti int',...
    'Bti Fe','Kao','Chl Fe','Chl Mg','Mg Clay','Mg Si','Ill Smec','Ill Smec Fe','Cal',...
    'Dol','Dol Fe','Fe ox si','Prt','Gyp Anh','Hlt','Rtl Ilm','Ilm','Ttn','Lmt','Cpx',...
    'Fe Amph','Epd Zo','Apt','Trml','Zrc','Calg','AlOx','Udf'};

minsN_abbv = {'blank','Qtz','Ksp','Plag','Mscv','Bti','Kao','Chl','Mg Clay','Mg Si','Ill Smec','Cal',...
    'Dol','Fe ox si','Prt','Gyp Anh','Hlt','Ilm','Ttn','Lmt','Cpx',...
    'Fe Amph','Epd Zo','Apt','Trml','Zrc','Calg','AlOx','Udf'};

minNFull = ...
{'Background', 'Quartz', 'K Feldspar', 'Plagioclase Ab', 'Plagioclase An25',...
'Plagioclase An50', 'Plagioclase An75','Muscovite', 'Biotite (Low Fe & Mg)',...
'Biotite (Mg-rich)', 'Biotite (Intermediate)', 'Biotite (Fe-rich)', 'Kaolinite',...
'Fe Chlorite', 'Mg Chlorite', 'Mg Clays', 'Mg Silicate', 'Illite & illite-smectite',...
'Fe-Illite & illite-smectite','Calcite', 'Dolomite', 'Ferroan Dolomite',...
'Fe Oxide & siderite', 'Pyrite', 'Gypsum / Anhydrite', 'Halite', 'Rutile & Ilmenite',...
'Ilmenite', 'Titanite', 'Laumontite', 'Clinopyroxene', 'Fe Amphibole', 'Epidote / Zoisite',...
'Apatite', 'Tourmaline', 'Zircon','Calgon', 'Aluminium Oxide','Undifferentiated'};

minNFull_abbv = ...
{'Background', 'Quartz', 'K Feldspar', 'Plagioclase','Muscovite', 'Biotite', 'Kaolinite',...
'Chlorite', 'Mg Clays', 'Mg Silicate', 'Illite-smectite','Calcite', 'Dolomite'...
'Fe Oxide & siderite', 'Pyrite', 'Gypsum / Anhydrite', 'Halite'...
'Ilmenite', 'Titanite', 'Laumontite', 'Clinopyroxene', 'Fe Amphibole', 'Epidote / Zoisite',...
'Apatite', 'Tourmaline', 'Zircon','Calgon', 'Aluminium Oxide','Undifferentiated'};


if dType == 1
        
    datOut = [datIn(1),datIn(2),datIn(3),...
        datIn(4)+datIn(5)+datIn(6)+datIn(7),...  %plagioclase
        datIn(8),datIn(9)+datIn(10)+datIn(11)+datIn(12),... %biotite
        datIn(13),...
        datIn(14)+datIn(15),...%chlorite
        datIn(16),datIn(17),...
        datIn(18)+datIn(19),... %illite
        datIn(20),...
        datIn(21)+datIn(22),... %dolomite
        datIn(23),datIn(24),datIn(25),datIn(26),...
        datIn(27)+datIn(28),... %ilmenite
        datIn(29:end)];
    
end

if dType == 2
    
    datOut = [datIn(:,1),datIn(:,2),datIn(:,3),...
        datIn(:,4)+datIn(:,5)+datIn(:,6)+datIn(:,7),...  %plagioclase
        datIn(:,8),datIn(:,9)+datIn(:,10)+datIn(:,11)+datIn(:,12),... %biotite
        datIn(:,13),...
        datIn(:,14)+datIn(:,15),...%chlorite
        datIn(:,16),datIn(:,17),...
        datIn(:,18)+datIn(:,19),... %illite
        datIn(:,20),...
        datIn(:,21)+datIn(:,22),... %dolomite
        datIn(:,23),datIn(:,24),datIn(:,25),datIn(:,26),...
        datIn(:,27)+datIn(:,28),... %ilmenite
        datIn(:,29:end)];
end

if dType == 3
    
    datIn = [datIn(:,1),datIn(:,2),datIn(:,3),...
        datIn(:,4)+datIn(:,5)+datIn(:,6)+datIn(:,7),...  %plagioclase
        datIn(:,8),datIn(:,9)+datIn(:,10)+datIn(:,11)+datIn(:,12),... %biotite
        datIn(:,13),...
        datIn(:,14)+datIn(:,15),...%chlorite
        datIn(:,16),datIn(:,17),...
        datIn(:,18)+datIn(:,19),... %illite
        datIn(:,20),...
        datIn(:,21)+datIn(:,22),... %dolomite
        datIn(:,23),datIn(:,24),datIn(:,25),datIn(:,26),...
        datIn(:,27)+datIn(:,28),... %ilmenite
        datIn(:,29:end)]
    
    datOut = [datIn(1,:);datIn(2,:);datIn(3,:);...
        datIn(4,:)+datIn(5,:)+datIn(6,:)+datIn(7,:);...  %plagioclase
        datIn(8,:);datIn(9,:)+datIn(10,:)+datIn(11,:)+datIn(12,:);... %biotite
        datIn(13,:);...
        datIn(14,:);+datIn(15,:);...%chlorite
        datIn(16,:);datIn(17,:);...
        datIn(18,:)+datIn(19,:);... %illite
        datIn(20,:);...
        datIn(21,:)+datIn(22,:);... %dolomite
        datIn(23,:);datIn(24,:);datIn(25,:);datIn(26,:);...
        datIn(27,:)+datIn(28,:);... %ilmenite
        datIn(29:end,:)]
    
end

if dType == 4
    
    datIn = [datIn(:,1,:),datIn(:,2,:),datIn(:,3,:),...
        datIn(:,4,:)+datIn(:,5,:)+datIn(:,6,:)+datIn(:,7,:),...  %plagioclase
        datIn(:,8,:),datIn(:,9,:)+datIn(:,10,:)+datIn(:,11,:)+datIn(:,12,:),... %biotite
        datIn(:,13,:),...
        datIn(:,14,:)+datIn(:,15,:),...%chlorite
        datIn(:,16,:),datIn(:,17,:),...
        datIn(:,18,:)+datIn(:,19,:),... %illite
        datIn(:,20,:),...
        datIn(:,21,:)+datIn(:,22,:),... %dolomite
        datIn(:,23,:),datIn(:,24,:),datIn(:,25,:),datIn(:,26,:),...
        datIn(:,27,:)+datIn(:,28,:),... %ilmenite
        datIn(:,29:end,:)]
    
    datOut = [datIn(1,:,:);datIn(2,:,:);datIn(3,:,:);...
        datIn(4,:,:)+datIn(5,:,:)+datIn(6,:,:)+datIn(7,:,:);...  %plagioclase
        datIn(8,:,:);datIn(9,:,:)+datIn(10,:,:)+datIn(11,:,:)+datIn(12,:,:);... %biotite
        datIn(13,:,:);...
        datIn(14,:,:);+datIn(15,:,:);...%chlorite
        datIn(16,:,:);datIn(17,:,:);...
        datIn(18,:,:)+datIn(19,:,:);... %illite
        datIn(20,:,:);...
        datIn(21,:,:)+datIn(22,:,:);... %dolomite
        datIn(23,:,:);datIn(24,:,:);datIn(25,:,:);datIn(26,:,:);...
        datIn(27,:,:)+datIn(28,:,:);... %ilmenite
        datIn(29:end,:,:)]
    
end

if dType == 5
  
    datIn(:,40) = datIn(:,4)+datIn(:,5)+datIn(:,6)+datIn(:,7);
    datIn(:,41) = datIn(:,9)+datIn(:,10)+datIn(:,11)+datIn(:,12);
    datIn(:,42) = datIn(:,14)+datIn(:,15);
    datIn(:,43) = datIn(:,18)+datIn(:,19);
    datIn(:,44) = datIn(:,21)+datIn(:,22);
    datIn(:,45) = datIn(:,27)+datIn(:,28);
    datIn(:,1) = [];
    datOut = datIn;

    minsN = {'Qtz','Ksp','Ab','An25','AN50','An75','Mscv','Bti low','Bti Mg','Bti int',...
    'Bti Fe','Kao','Chl Fe','Chl Mg','Mg Clay','Mg Si','Ill Smec','Ill Smec Fe','Cal',...
    'Dol','Dol Fe','Fe ox si','Prt','Gyp Anh','Hlt','Rtl Ilm','Ilm','Ttn','Lmt','Cpx',...
    'Fe Amph','Epd Zo','Apt','Trml','Zrc','Calg','AlOx','Udf','Plag A','Biot A','Chlor A',...
    'Ill smec A','Dol A','Ilm A'};
    minsNFull = {'Qtz','Ksp','Ab','An25','AN50','An75','Mscv','Bti_low','Bti_Mg','Bti_int',...
    'Bti_Fe','Kao','Chl_Fe','Chl_Mg','Mg_Clay','Mg_Si','Ill_Smec','Ill_Smec_Fe','Cal',...
    'Dol','Dol_Fe','Fe_ox_si','Prt','Gyp_Anh','Hlt','Rtl_Ilm','Ilm','Ttn','Lmt','Cpx',...
    'Fe_Amph','Epd_Zo','Apt','Trml','Zrc','Calg','AlOx','Udf','Plag_A','Biot_A','Chlor_A',...
    'Ill_smec_A','Dol_A','Ilm_A'};
    
end

    
end
    