function [datOut,minsN_abbv,minNFull_abbv] = abbvMins(datIn,dType)

%here dType = 1 for vector, 2 for rows of grains and columns of minerals (mnrlMtx),
%and 3 for a mineral correlation matrix. 

minsN = {'blank','Qtz','Ksp','Ab','An25','AN50','An75','Mscv','Bti low','Bti Mg','Bti int',...
    'Bti Fe','Kao','Chl Fe','Chl Mg','Mg Clay','Mg Si','Ill Smec','Ill Smec Fe','Cal',...
    'Dol','Dol Fe','Fe ox si','Prt','Gyp Anh','Hlt','Rtl Ilm','Ilm','Ttn','Lmt','Cpx',...
    'Fe Amph','Epd Zo','Apt','Trml','Zrc','Calg','AlOx','Udf'};

minsN_abbv = {'blank','Qtz','Ksp','Plag','Mscv','Bti','Kao','Chl Fe','Chl Mg','Mg Clay','Mg Si','Ill Smec','Cal',...
    'Dol','Fe ox si','Prt','Gyp Anh','Hlt','Ilm','Ttn','Lmt','Cpx',...
    'Fe Amph','Epd Zo','Apt','Trml','Zrc','Calg','AlOx','Udf'}

minNFull = ...
{'Background', 'Quartz', 'K Feldspar', 'Plagioclase Ab', 'Plagioclase An25',...
'Plagioclase An50', 'Plagioclase An75','Muscovite', 'Biotite (Low Fe & Mg)',...
'Biotite (Mg-rich)', 'Biotite (Intermediate)', 'Biotite (Fe-rich)', 'Kaolinite',...
'Fe Chlorite', 'Mg Chlorite', 'Mg Clays', 'Mg Silicate', 'Illite & illite-smectite',...
'Fe-Illite & illite-smectite','Calcite', 'Dolomite', 'Ferroan Dolomite',...
'Fe Oxide & siderite', 'Pyrite', 'Gypsum / Anhydrite', 'Halite', 'Rutile & Ilmenite',...
'Ilmenite', 'Titanite', 'Laumontite', 'Clinopyroxene', 'Fe Amphibole', 'Epidote / Zoisite',...
'Apatite', 'Tourmaline', 'Zircon','Calgon', 'Aluminium Oxide','Undifferentiated'};

minNFull_abbv = ...
{'Background', 'Quartz', 'K Feldspar', 'Plagioclase','Muscovite', 'Biotite', 'Kaolinite',...
'Fe Chlorite', 'Mg Chlorite', 'Mg Clays', 'Mg Silicate', 'Illite-smectite','Calcite', 'Dolomite'...
'Fe Oxide & siderite', 'Pyrite', 'Gypsum / Anhydrite', 'Halite'...
'Ilmenite', 'Titanite', 'Laumontite', 'Clinopyroxene', 'Fe Amphibole', 'Epidote / Zoisite',...
'Apatite', 'Tourmaline', 'Zircon','Calgon', 'Aluminium Oxide','Undifferentiated'};


if dType == 1
        
    datOut = [datIn(1),datIn(2),datIn(3),...
        datIn(4)+datIn(5)+datIn(6)+datIn(7),...  %plagioclase
        datIn(8),datIn(9)+datIn(10)+datIn(11)+datIn(12),... %biotite
        datIn(13),datIn(14),datIn(15),datIn(16),datIn(17),...
        datIn(18)+datIn(19),... %illite
        datIn(20),...
        datIn(21)+datIn(22),... %dolomite
        datIn(23),datIn(24),datIn(25),datIn(26),...
        datIn(27)+datIn(28),... %ilmenite
        datIn(29:end)];
    
end

if dType == 2
    
    datOut = [datIn(:,1),datIn(:,2),datIn(:,3),...
        datIn(:,4)+datIn(:,5)+datIn(:,6)+datIn(:,7),...  %plagioclase
        datIn(:,8),datIn(:,9)+datIn(:,10)+datIn(:,11)+datIn(:,12),... %biotite
        datIn(:,13),datIn(:,14),datIn(:,15),datIn(:,16),datIn(:,17),...
        datIn(:,18)+datIn(:,19),... %illite
        datIn(:,20),...
        datIn(:,21)+datIn(:,22),... %dolomite
        datIn(:,23),datIn(:,24),datIn(:,25),datIn(:,26),...
        datIn(:,27)+datIn(:,28),... %ilmenite
        datIn(:,29:end)];
end

if dType == 3
    
    datIn = [datIn(:,1),datIn(:,2),datIn(:,3),...
        datIn(:,4)+datIn(:,5)+datIn(:,6)+datIn(:,7),...  %plagioclase
        datIn(:,8),datIn(:,9)+datIn(:,10)+datIn(:,11)+datIn(:,12),... %biotite
        datIn(:,13),datIn(:,14),datIn(:,15),datIn(:,16),datIn(:,17),...
        datIn(:,18)+datIn(:,19),... %illite
        datIn(:,20),...
        datIn(:,21)+datIn(:,22),... %dolomite
        datIn(:,23),datIn(:,24),datIn(:,25),datIn(:,26),...
        datIn(:,27)+datIn(:,28),... %ilmenite
        datIn(:,29:end)]
    
    datOut = [datIn(1,:);datIn(2,:);datIn(3,:);...
        datIn(4,:)+datIn(5,:)+datIn(6,:)+datIn(7,:);...  %plagioclase
        datIn(8,:);datIn(9,:)+datIn(10,:)+datIn(11,:)+datIn(12,:);... %biotite
        datIn(13,:);datIn(14,:);datIn(15,:);datIn(16,:);datIn(17,:);...
        datIn(18,:)+datIn(19,:);... %illite
        datIn(20,:);...
        datIn(21,:)+datIn(22,:);... %dolomite
        datIn(23,:);datIn(24,:);datIn(25,:);datIn(26,:);...
        datIn(27,:)+datIn(28,:);... %ilmenite
        datIn(29:end,:)]
    
end

if dType == 4
    
    datIn = [datIn(:,1,:),datIn(:,2,:),datIn(:,3,:),...
        datIn(:,4,:)+datIn(:,5,:)+datIn(:,6,:)+datIn(:,7,:),...  %plagioclase
        datIn(:,8,:),datIn(:,9,:)+datIn(:,10,:)+datIn(:,11,:)+datIn(:,12,:),... %biotite
        datIn(:,13,:),datIn(:,14,:),datIn(:,15,:),datIn(:,16,:),datIn(:,17,:),...
        datIn(:,18,:)+datIn(:,19,:),... %illite
        datIn(:,20,:),...
        datIn(:,21,:)+datIn(:,22,:),... %dolomite
        datIn(:,23,:),datIn(:,24,:),datIn(:,25,:),datIn(:,26,:),...
        datIn(:,27,:)+datIn(:,28,:),... %ilmenite
        datIn(:,29:end,:)]
    
    datOut = [datIn(1,:,:);datIn(2,:,:);datIn(3,:,:);...
        datIn(4,:,:)+datIn(5,:,:)+datIn(6,:,:)+datIn(7,:,:);...  %plagioclase
        datIn(8,:,:);datIn(9,:,:)+datIn(10,:,:)+datIn(11,:,:)+datIn(12,:,:);... %biotite
        datIn(13,:,:);datIn(14,:,:);datIn(15,:,:);datIn(16,:,:);datIn(17,:,:);...
        datIn(18,:,:)+datIn(19,:,:);... %illite
        datIn(20,:,:);...
        datIn(21,:,:)+datIn(22,:,:);... %dolomite
        datIn(23,:,:);datIn(24,:,:);datIn(25,:,:);datIn(26,:,:);...
        datIn(27,:,:)+datIn(28,:,:);... %ilmenite
        datIn(29:end,:,:)]
    
end

        
    
end
    